deployment:
  tasks:
    # Define caminho base
    - export DEPLOYPATH=/home/mmbsites/conectedu.mmbsites.com.br

    # Copia o index.php da raiz
    - /bin/cp index.php $DEPLOYPATH/

    # Copia o frontend para a pasta /frontend do site
    - /bin/mkdir -p $DEPLOYPATH/frontend
    - /bin/cp -R frontend/* $DEPLOYPATH/frontend

    # Copia o backend para a pasta /backend do site
    - /bin/mkdir -p $DEPLOYPATH/backend
    - /bin/cp -R backend/* $DEPLOYPATH/backend

    # Executa as migrações do banco de dados
    - cd $DEPLOYPATH/backend && /usr/bin/php -f migrations.php

    # Cria o usuário admin padrão (se não existir)
    - cd $DEPLOYPATH/backend && /usr/bin/php -f create_admin.php
